# Cluster stability and concordance

## Sankey plot
```{r sankeyplot}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("scmap", update = FALSE)
library(scmap)

# create dataframe for sankey plot between clusters

df_sankey <- merge(df_surv, df_surv_w, by = "ID")
selected_columns <- c("c_name", "c_name_w", "ID")
df_sankey <- df_sankey[,selected_columns]

# create sankey plot
sankey <- getSankey(df_sankey[,'c_name'], df_sankey[,'c_name_w'], plot_width = 400, plot_height = 600,
  colors = c("#357ABD", "#559E4B", "#734173", "#edbd08"))
plot(sankey)

# count numbers
same_group <- sum(df_sankey$c_name == df_sankey$c_name_w)
different_group <- sum(df_sankey$c_name != df_sankey$c_name_w)
transfer_matrix <- table(df_sankey$c_name, df_sankey$c_name_w)

cat("Number of individuals staying in the same group:", same_group, "\n")
cat("Number of individuals transferring to different groups:", different_group, "\n")
print("Transfer matrix:")
print(transfer_matrix)
write.xlsx(transfer_matrix, file = "../Output/sankey_numbers.xlsx", rowNames = F)
```


# Cluster stability
## Original list

```{r cluster_stability_T}
# Determine the stability
# 1. KMeans(pam clustering)
data.scld_1 <- data.scld %>% select(one_of(modeller))

# use distance matrix as inputs
res_post_noDM_stable_kmeans <- clusterboot(gow_dist, distances = T,
                                           B = 100, bootmethod = c("boot"), 
                                           clustermethod = pamkCBI,
                                           seed = 123,
                                           count = FALSE,
                                           k = 4) 

temp <- res_post_noDM_stable_kmeans$bootresult %>% t() %>% data.frame() %>% 
  dplyr::rename(
         Cluster1 = X1,
         Cluster2 = X2,
         Cluster3 = X3,
         Cluster4 = X4
  )

## Using gather function to change wide data to long
temp_long <- gather(temp, Cluster, Value, Cluster1:Cluster4)

str(temp_long)
## Calculate mean, sd, se, and IC
temp_long <- temp_long  %>% 
  dplyr::group_by(Cluster) %>% 
  summarise(n = n(),
            mean = mean(Value),
            sd = sd(Value)) %>% 
  mutate(se = sd/sqrt(n)) %>%
  mutate(ic = se * qt((1-0.05)/2 + .5, n-1)) 

## Barplot
Jaccard_KM <- ggplot(temp_long, aes(x = Cluster, y = mean, fill = Cluster)) +
  geom_bar(stat = "identity", alpha = 0.5, width = 0.5) +
  geom_errorbar(aes(x = Cluster, ymin = mean-ic, ymax = mean+ic), width = 0.2, color = "black", alpha = 0.6, size = 1) +
  labs(x = NULL, y = "Jaccard Index") + theme_bw()

```

## Proxy list

```{r cluster_stability_W}

# Determine the stability
# 1. KMeans -> pamk cluster -> distance change to (gower distance)
data.scld_w_1 <- data.scld_w %>% select(one_of(modeller_w))

res_post_noDM_stable_kmeans_w <- clusterboot(gow_dist_w, 
                                             distances = T,
                                             B = 100, bootmethod = c("boot"), 
                                             clustermethod = pamkCBI,
                                             seed = 123, count = FALSE,
                                             k = 4) 

temp_w <- res_post_noDM_stable_kmeans_w$bootresult %>% t() %>% data.frame() %>% 
  dplyr::rename(Cluster1 = X1,
         Cluster2 = X2,
         Cluster3 = X3,
         Cluster4 = X4)


## Using gather function to change wide data to long
temp_long_w <- gather(temp_w, Cluster, Value, Cluster1:Cluster4)

## Calculate mean, sd, se, and IC
temp_long_w <- temp_long_w %>% 
  group_by(Cluster) %>% 
  summarise(n = n(),
            mean = mean(Value),
            sd = sd(Value)) %>% 
  mutate(se = sd/sqrt(n)) %>%
  mutate(ic = se * qt((1-0.05)/2 + .5, n-1))

## Barplot
Jaccard_KM_w <- ggplot(temp_long_w, aes(x = Cluster, y = mean, fill = Cluster)) +
  geom_bar(stat = "identity", alpha = 0.5, width = 0.5) +
  geom_errorbar(aes(x = Cluster, ymin = mean-ic, ymax = mean+ic), width = 0.2, color = "black", alpha = 0.6, size = 1) +
  labs(x = NULL, y = "Jaccard Index - ") + theme_bw()


par(mfrow = c(2,1))




```

## Print plots
```{r}
combined_plot_J <- Jaccard_KM / Jaccard_KM_w

ggsave("../Output/plot_stability.png", combined_plot_J, width = 5, height = 8, dpi = 500)

```

