# Metabolomics
```{r}
rm(list = ls())
source("00_functions.R")
```

## Exclude metabolite ratios and postprandial

```{r metabolomics_setup}
# new df with cluster assignment and all metabolites

load(file = "./Results/Survivial.Rdata")

df_rf <- df_surv %>% select(XXLVLDLP_1:Gp_3, cluster)

df_rf_w <- df_surv_w %>% select(XXLVLDLP_1:Gp_3, cluster_w)

# import file with variable names that should be excluded
metab_exc <- read.csv("../Data/Metabolite_Ratios_list.csv")
metab_exc_v <- metab_exc$x

# also exclude postprandial
post_pran <- names(df_rf)[endsWith(names(df_rf), "_3")]

# combine metab and postprandial
metab_pran <- union(metab_exc_v, post_pran)

# make df with fasting and postprandial
df_rf_fp <- df_rf %>%
  select(!all_of(metab_exc_v))

```

```{r remove_outliers}
# Replace any value <= 0 with NA
df_rf_fp <- df_rf_fp %>% mutate_at(vars(XXLVLDLP_1:Gp_3), ~ifelse(.<=0,NA,.))       # for fasting and postprandial

w_2 <- apply(df_rf_fp[,c(1:296)], 2, function(x) is_outlier(x, nSD = 5)) # list: 296 metabolites, more than 5 SD

# Replace outliers with NA - fasting and postprandial
for (i in names(w_2)) {
  a <- w_2[[i]]
  if (!is.null(a)){
    df_rf_fp[a, i] <- NA
  }
}

```

### Remove missings in individuals (>40%)

```{r remove_missings_individual}
df_rf_fp$fmis_sample = apply(df_rf_fp[,c(1:296)], 1,  function(x) { sum(is.na(x)) / length(x)})
df_rf_fp <- subset(df_rf_fp, fmis_sample <= 0.4) # 1477 observations
# df_rf_fp <- df_rf_fp %>% select(c(XXLVLDLP_1:cluster),)

```

## Remove missings in metabolites (>10%)
```{r remove_missings_metab}
# Filter metabolites with >10% missing
fmis = apply(df_rf_fp, 2,  function(x) {sum(is.na(x)) / length(x)})

# Filter samples
fmis_df <- as.data.frame(fmis)
fmis_df <- fmis_df %>% rownames_to_column(var = "Meta_status")
fmis_df$Group <-  str_split(fmis_df$Meta_status, "_", simplify = T)[,2]
fmis_df$Group <- ifelse(fmis_df$Group == "1", "Fasting_state", "Postprandial_state")
fmis_df <- fmis_df[order(fmis_df$fmis),]
fmis_df  <- fmis_df %>% 
  group_by(Group) %>% 
  arrange(desc(fmis)) %>% 
  ungroup()

w = which(fmis > 0.1) # 10 metabolites with missing rate > 10%
Removemetabolites <- names(w) 
Removemetabolites_fasting <- Removemetabolites[grep("_1", Removemetabolites)] # in the fasting
Removemetabolites_postprandial <- Removemetabolites[grep("_3", Removemetabolites)] # in the postprandial

df_fp <- df_rf_fp %>% 
  select(!any_of(Removemetabolites))

```

# scaling for the metabolite measures
```{r rf_final_check}
# Scaling
df_rf_met_num <- df_fp %>% 
   mutate_at(c(1:276), as.numeric) %>%
   mutate_at(c(1:276), funs(c(scale(.))))

## Impute low values
# impute with min/2

df_rf_tot <- impute_min2(df_rf_met_num)

## fasting
post_pran <- names(df_rf_tot)[endsWith(names(df_rf_tot), "_3")]
df_rf_met <- df_rf_tot %>% select(!all_of(post_pran))

```

## Random forest
```{r RF_TUEF_withoutiPVS}
set.seed(71)

# beta cell failure, 1 = high risk, 2 = all others -> intermediate-higher subtype
df_rf_met$cluster_b <- as.factor(ifelse(df_rf_met$cluster == "2", "1", "2")) 

# high risk visceral fat -> intermediate risk subtype
df_rf_met$cluster_hrv <- as.factor(ifelse(df_rf_met$cluster == "4", "1", "2"))

# high risk insulin resistance -> high risk subtype
df_rf_met$cluster_hri <- as.factor(ifelse(df_rf_met$cluster == "1", "1", "2"))           

# Beta cell failure -> intermediate-higher subtype
df_rf_b <- df_rf_met %>%  select(LVLDLP_1:Gp_1, cluster_b)
rf_b <-randomForest(cluster_b~.,data=df_rf_b, ntree=500, localImp = TRUE) 
r_imp_b <- importance(rf_b)
# importance_frame_b <- measure_importance(rf_b)

# High risk visceral fat -> intermediate risk subtype
df_rf_hrv <- df_rf_met %>% select(LVLDLP_1:Gp_1, cluster_hrv)
rf_hrv <-randomForest(cluster_hrv~.,data=df_rf_hrv, ntree=500, localImp = TRUE) 
r_imp_hrv <- importance(rf_hrv)
# importance_frame_hrv <-measure_importance(rf_hrv)

# HR IR -> high risk subtype
df_rf_hri <- df_rf_met %>% select(LVLDLP_1:Gp_1, cluster_hri)
rf_hri <- randomForest(cluster_hri~.,data=df_rf_hri, ntree=500, localImp = TRUE) 
r_imp_hri <- importance(rf_hri)
# importance_frame_hri <-measure_importance(rf_hri)

## Create table with top 10
## beta cell
df_met10_b <- r_imp_b %>% as.data.frame() %>% rownames_to_column() %>% 
   select(rowname, MeanDecreaseAccuracy , MeanDecreaseGini)
sorted_data_b <- df_met10_b[order(-df_met10_b$MeanDecreaseAccuracy, -df_met10_b$MeanDecreaseGini),]

# select the top 10 metabolites
top_10_b <- sorted_data_b %>%
  slice_head(n=10) 

# HRV
df_met10_hrv <- r_imp_hrv %>% as.data.frame() %>% rownames_to_column() %>% 
   select(rowname, MeanDecreaseAccuracy, MeanDecreaseGini)
sorted_data_hrv <- df_met10_hrv[order(-df_met10_hrv$MeanDecreaseAccuracy, -df_met10_b$MeanDecreaseGini),]

# select the top 10 metabolites for viseral fat
top_10_hrv <- sorted_data_hrv %>%
     slice_head(n=10) 

# HRI
df_met10_hri <- r_imp_hri %>% as.data.frame() %>% rownames_to_column() %>% 
   select(rowname, MeanDecreaseAccuracy, MeanDecreaseGini)
sorted_data_hri <- df_met10_hri[order(-df_met10_hri$MeanDecreaseAccuracy, -df_met10_b$MeanDecreaseGini),]

# select the top 10 metabolites for IR group
top_10_hri <- sorted_data_hri %>%
  slice_head(n=10)

save(sorted_data_hri, sorted_data_hrv, sorted_data_b, file = "./Results/metabolites_RF_v2.Rdata")
```

```{r}
varImpPlot(rf_b)
varImpPlot(rf_hrv)
varImpPlot(rf_hri)
```


## plot the results

```{r RF_TUEF_withoutiPVS}
# plot the lollipop plot for important metabolites
library(data.table)
library(ggalt)
library(reshape2)

group_stat <- c("Top 10 Metabolites in Intermediate-risk subtype", "Top 10 Metabolites in Intermediate-high risk subtype", "Top 10 Metabolites in high risk subtype")
group_rf <- c( "rf_hrv", "rf_b", "rf_hri")
titles <- setNames(group_stat, group_rf)

lollipop_metabolites <- list()
for (group_rf_index in group_rf) {
  
  imp <- data.table(importance(get(group_rf_index)), keep.rownames = TRUE)
  
  # imp = melt(imp, id.vars="rn")
  # select the first 10 metabolites
  # imp_filter <- imp %>% 
  #   filter(variable == "MeanDecreaseAccuracy") %>% 
  #   arrange(desc(value)) %>% 
  #   slice_head(n = 10) %>% 
  #   select(rn, value)
  
  imp_filter <- imp %>% 
    select(rn, MeanDecreaseAccuracy) %>% 
    arrange(desc(MeanDecreaseAccuracy)) %>% 
    slice_head(n = 10)
  
  imp_filter[, rn := factor(rn, levels = rev(unique(rn)))]
  
  p <- ggplot(imp_filter, 
         aes(x = rn, y = MeanDecreaseAccuracy, 
             label = round(MeanDecreaseAccuracy, 1))) + 
    geom_lollipop(point.size = 2, point.colour = "steelblue", color = "darkgreen") +
    geom_text(nudge_y = 0.8, size = 3) +
    coord_flip() +
    theme_bw() +
    xlab("") +
    ggtitle(titles[group_rf_index]) +
    ylab("Mean_accuracy_decrease") +
    theme(panel.grid.major.y=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5, size = 10, face = "bold"))
  
  lollipop_metabolites[[group_rf_index]] <- p
 
}

# ggarrange to combine the plots

# Create an empty plot with a white background
empty_plot <- ggplot() + theme_void() + 
    theme(
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA)
  )

p_tot <- ggarrange(
  # Figure 1
  ggarrange(lollipop_metabolites[[1]],
            lollipop_metabolites[[2]], ncol = 2, 
            labels = c("A", "B"),
            widths = c(1/2, 1/2),
            font.label = list(size = 14)),
  
  # Figure 2
  ggarrange(lollipop_metabolites[[3]], empty_plot, 
            ncol = 2,
            labels = c("C", ""),
            widths = c(1/2, 1/2),
            font.label = list(size = 14)),
  nrow = 2,
  heights = c(1/2, 1/2)
) 

p_tot

pdf(file = "./Results/Top10_Key_Metabolites_v2.pdf", width = 10, height = 10)
p_tot
dev.off()
# ggsave('./Results/Top10_Key_Metabolites.png', p_tot, width = 10, height = 10, dpi = 300)
```

# Table metabolomics output
### Total table

```{r table_rf_results}
# Create data frame with all top 10s for TUEF and WH
df_rf_tot <- data.frame(top_10_hrv, top_10_b, top_10_hri)

# Change to character
df_rf_tot <- df_rf_tot %>% mutate(across(everything(), as.character)) %>% 
  dplyr::select(starts_with("rowname"))

# delete rownames
rownames(df_rf_tot) <- NULL

# create titles for columns
titles_rf <- c("Intermediate-risk subtype", "Intermediate-high-risk subtype",  "High-risk subtype")
colnames(df_rf_tot) <- titles_rf

# print table
df_rf_tot

write.csv(df_rf_tot, file = "./Results/RF_outcomes_metab_v2.csv")
```
```{r}
intersect(df_rf_tot$`Intermediate-risk subtype`, df_rf_tot$`Intermediate-high-risk subtype`)
intersect(df_rf_tot$`Intermediate-high-risk subtype`, df_rf_tot$`High-risk subtype`)
intersect(df_rf_tot$`Intermediate-risk subtype`, df_rf_tot$`High-risk subtype`)

# Gp_1 and Glc_1 are shared by all of the subtypes 
```




